name: rsreu_compilers
description: Compilers course.
version: 3.0.0
repository: https://github.com/zekfad/rsreu_compilers

environment:
  sdk: ^3.2.0-0

dependencies:
  args: ^2.4.2
  meta: ^1.11.0

dev_dependencies:
  zekfad_lints: ^1.0.0
